gen:
	fvm flutter pub run build_runner build --delete-conflicting-outputs

get:
	fvm flutter pub get

reincarnate:
	fvm flutter clean & fvm flutter doctor & fvm flutter pub get

open_xcode:
	open ios/Runner.xcworkspace

build_apk:
	fvm flutter build apk --release